export const studentsInputs = [
  {
    id: 1,
    label: "Username",
    name: "username",
    type: "text",
    placeholder: "smith_rowe",
  },
  {
    id: 2,
    label: "Name and Surname",
    name: "name",
    type: "text",
    placeholder: "Smith Rowe",
  },
  {
    id: 3,
    label: "Email",
    name: "email",
    type: "email",
    placeholder: "smith_rowe@gmail.com",
  },
  {
    id: 4,
    label: "Phone",
    name: "phone",
    type: "text",
    placeholder: "+1 234-234-545",
  },
  {
    id: 5,
    label: "Password",
    name: "password",
    type: "password",
    placeholder: "Enter your password",
  },
  {
    id: 6,
    label: "Address",
    name: "address",
    type: "text",
    placeholder: "Melwood str. Liverpool",
  },
  {
    id: 6,
    label: "Country",
    name: "country",
    type: "text",
    placeholder: "United Kingdom",
  },
];
export const houseOwnerInputs = [
  {
    id: 1,
    label: "Username",
    name: "username",
    type: "text",
    placeholder: "smith_rowe",
  },
  {
    id: 2,
    label: "Name and Surname",
    name: "name",
    type: "text",
    placeholder: "Smith Rowe",
  },
  {
    id: 3,
    label: "Email",
    name: "email",
    type: "email",
    placeholder: "smith_rowe@gmail.com",
  },
  {
    id: 4,
    label: "Phone",
    name: "phone",
    type: "text",
    placeholder: "+1 234-234-545",
  },
  {
    id: 5,
    label: "Password",
    name: "password",
    type: "password",
    placeholder: "Enter your password",
  },
  {
    id: 6,
    label: "Address",
    name: "address",
    type: "text",
    placeholder: "Melwood str. Liverpool",
  },
  {
    id: 6,
    label: "Country",
    name: "country",
    type: "text",
    placeholder: "United Kingdom",
  },
];
